### ISSUE TITLE
Connect with MongoDB

### ISSUE THREAD

**Issue by vkrunal** [Sehat-Intel/SehatIntel-FlaskPredict#1]
Connect the App with MongoDB 

 - call the X-ray images from it 
 - predict the output 
 - store back the Predicted Class in MongoDB.

**Comment by tuminzee** [comment]
Db connection done
I will structure the code, and close the issue with an appropriate commit

**Comment by tuminzee** [comment]
I am adding some helpful resource
- https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications
- https://flask.palletsprojects.com/en/1.1.x/tutorial/layout/
- https://exploreflask.com/en/latest/configuration.html
- https://www.youtube.com/watch?v=MbXEQZZSvzk
